from typing import Any, Sequence

class _Column:
    def metric(self, label: str, value: str) -> None: ...

class _Sidebar:
    def selectbox(
        self,
        label: str,
        options: Sequence[str],
        *,
        index: int,
        help: str | None = ...,
    ) -> str: ...

sidebar: _Sidebar

def set_page_config(*, page_title: str, layout: str) -> None: ...
def subheader(body: str) -> None: ...
def columns(spec: int) -> list[_Column]: ...
def button(label: str, *, type: str = ...) -> bool: ...
def rerun() -> None: ...
def warning(body: str) -> None: ...
def error(body: str) -> None: ...
def success(body: str) -> None: ...
def caption(body: str) -> None: ...
def title(body: str) -> None: ...
def metric(label: str, value: str) -> None: ...
def dataframe(data: Any, *, use_container_width: bool, hide_index: bool) -> None: ...
